name: restyle

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 19.1.0

jobs:
  build-ts:
    name: 'Build Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          yarn build
  build-fixture-ts:
    name: 'Build fixture Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          cd fixture
          yarn
          yarn build:android
          yarn build:ios
  lint-ts:
    name: 'Lint Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          yarn lint
  test-ts:
    name: 'Test Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          yarn test --forceExit
  build-android:
    name: 'Build Android'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: |
          bundle install
          cd fixture
          yarn
          cd android
          ./gradlew assembleDebug
